# --- Qatten specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "qplex_decomm_learner"
double_q: True
mixer: "dmaq_qatten"
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_layers: 1
adv_hypernet_embed: 64

num_kernel: 4
is_minus_one: True
weighted_head: True
is_adv_attention: True
is_stop_gradient: True

n_head: 4  # attention head number
attend_reg_coef: 0.001
state_bias: True  # the constant value c(s) in the paper
mask_dead: False
weighted_head: False
nonlinear: False

burn_in_period: 100

# DeComm specific parameters
mac: "decomm_mac"
agent: "decomm_rnn"
att_heads: 4
att_embed_dim: 32
optimizer: "adam"
communication: True
comm_agents: 4
quantify: False # Whether to quantify communication data based on reward

name: "qplex_decomm"
