# --- VDN specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_decomm_learner"
double_q: True
mixer: "vdn"

# DeComm specific parameters
mac: "decomm_mac"
agent: "decomm_rnn"
att_heads: 4
att_embed_dim: 32
optimizer: "adam"
communication: True
comm_agents: 4
quantify: False # Whether to quantify communication data based on reward

name: "vdn_decomm"
